//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-nettet.dk/ToolboxGateway/2011/04/01/")]
[System.Xml.Serialization.XmlRootAttribute("Besked", Namespace="http://e-nettet.dk/ToolboxGateway/2011/04/01/", IsNullable=false)]
public partial class BeskedType {
    
    private HeaderType headerField;
    
    private System.Xml.XmlNode bodyField;
    
    /// <remarks/>
    public HeaderType Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-nettet.dk/ToolboxGateway/2011/04/01/")]
public partial class HeaderType {
    
    private string sagsreferenceField;
    
    private int kommunenummerField;
    
    private int ejendomsnummerField;
    
    private System.Nullable<bool> anvendBase64EncodeField;
    
    private bool anvendBase64EncodeFieldSpecified;
    
    /// <remarks/>
    public string Sagsreference {
        get {
            return this.sagsreferenceField;
        }
        set {
            this.sagsreferenceField = value;
        }
    }
    
    /// <remarks/>
    public int Kommunenummer {
        get {
            return this.kommunenummerField;
        }
        set {
            this.kommunenummerField = value;
        }
    }
    
    /// <remarks/>
    public int Ejendomsnummer {
        get {
            return this.ejendomsnummerField;
        }
        set {
            this.ejendomsnummerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> AnvendBase64Encode {
        get {
            return this.anvendBase64EncodeField;
        }
        set {
            this.anvendBase64EncodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AnvendBase64EncodeSpecified {
        get {
            return this.anvendBase64EncodeFieldSpecified;
        }
        set {
            this.anvendBase64EncodeFieldSpecified = value;
        }
    }
}
