//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace FRestgaeld6 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.realkreditnettet.dk/FRestgaeld6")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.realkreditnettet.dk/FRestgaeld6", IsNullable=false)]
    public partial class FRestgaeld6 {
        
        private DOCINF dOCINFField;
        
        private INSTIT iNSTITField;
        
        private EJDMID eJDMIDField;
        
        private LAANID lAANIDField;
        
        private RESTAN rESTANField;
        
        private AMORTF aMORTFField;
        
        /// <remarks/>
        public DOCINF DOCINF {
            get {
                return this.dOCINFField;
            }
            set {
                this.dOCINFField = value;
            }
        }
        
        /// <remarks/>
        public INSTIT INSTIT {
            get {
                return this.iNSTITField;
            }
            set {
                this.iNSTITField = value;
            }
        }
        
        /// <remarks/>
        public EJDMID EJDMID {
            get {
                return this.eJDMIDField;
            }
            set {
                this.eJDMIDField = value;
            }
        }
        
        /// <remarks/>
        public LAANID LAANID {
            get {
                return this.lAANIDField;
            }
            set {
                this.lAANIDField = value;
            }
        }
        
        /// <remarks/>
        public RESTAN RESTAN {
            get {
                return this.rESTANField;
            }
            set {
                this.rESTANField = value;
            }
        }
        
        /// <remarks/>
        public AMORTF AMORTF {
            get {
                return this.aMORTFField;
            }
            set {
                this.aMORTFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/FRestgaeld6")]
    public partial class DOCINF {
        
        private Meddelelsens_navn meddelelsens_navnField;
        
        private bool meddelelsens_navnFieldSpecified;
        
        private Meddelelsens_type meddelelsens_typeField;
        
        private bool meddelelsens_typeFieldSpecified;
        
        private string sender_versionField;
        
        private string modtager_versionField;
        
        private string onsket_versionField;
        
        private string informationsstromsnavnField;
        
        private string meddelelsens_nummerField;
        
        private Kodeliste5 meddelelsens_funktionField;
        
        private string datoField;
        
        private string afsender_partidField;
        
        private string iDkodeField;
        
        private string virksomhedsIDField;
        
        private string afdelingsidField;
        
        private string personidField;
        
        private string modtager_partidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Meddelelsens_navn Meddelelsens_navn {
            get {
                return this.meddelelsens_navnField;
            }
            set {
                this.meddelelsens_navnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Meddelelsens_navnSpecified {
            get {
                return this.meddelelsens_navnFieldSpecified;
            }
            set {
                this.meddelelsens_navnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Meddelelsens_type Meddelelsens_type {
            get {
                return this.meddelelsens_typeField;
            }
            set {
                this.meddelelsens_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Meddelelsens_typeSpecified {
            get {
                return this.meddelelsens_typeFieldSpecified;
            }
            set {
                this.meddelelsens_typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Sender_version {
            get {
                return this.sender_versionField;
            }
            set {
                this.sender_versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Modtager_version {
            get {
                return this.modtager_versionField;
            }
            set {
                this.modtager_versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Onsket_version {
            get {
                return this.onsket_versionField;
            }
            set {
                this.onsket_versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Informationsstromsnavn {
            get {
                return this.informationsstromsnavnField;
            }
            set {
                this.informationsstromsnavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Meddelelsens_nummer {
            get {
                return this.meddelelsens_nummerField;
            }
            set {
                this.meddelelsens_nummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Kodeliste5 Meddelelsens_funktion {
            get {
                return this.meddelelsens_funktionField;
            }
            set {
                this.meddelelsens_funktionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Dato {
            get {
                return this.datoField;
            }
            set {
                this.datoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Afsender_partid {
            get {
                return this.afsender_partidField;
            }
            set {
                this.afsender_partidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ID-kode")]
        public string IDkode {
            get {
                return this.iDkodeField;
            }
            set {
                this.iDkodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VirksomhedsID {
            get {
                return this.virksomhedsIDField;
            }
            set {
                this.virksomhedsIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Afdelingsid {
            get {
                return this.afdelingsidField;
            }
            set {
                this.afdelingsidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Personid {
            get {
                return this.personidField;
            }
            set {
                this.personidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Modtager_partid {
            get {
                return this.modtager_partidField;
            }
            set {
                this.modtager_partidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/FRestgaeld6")]
    public enum Meddelelsens_navn {
        
        /// <remarks/>
        Z06,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/FRestgaeld6")]
    public enum Meddelelsens_type {
        
        /// <remarks/>
        REQDOC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/FRestgaeld6")]
    public enum Kodeliste5 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("53")]
        Item53,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/FRestgaeld6")]
    public partial class AMORTF {
        
        private Kodeliste1 onskes_amortoplysningerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Kodeliste1 Onskes_amortoplysninger {
            get {
                return this.onskes_amortoplysningerField;
            }
            set {
                this.onskes_amortoplysningerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/FRestgaeld6")]
    public enum Kodeliste1 {
        
        /// <remarks/>
        Ja,
        
        /// <remarks/>
        Nej,
        
        /// <remarks/>
        IA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/FRestgaeld6")]
    public partial class RESTAN {
        
        private Kodeliste1 onskes_restanceoplysningerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Kodeliste1 Onskes_restanceoplysninger {
            get {
                return this.onskes_restanceoplysningerField;
            }
            set {
                this.onskes_restanceoplysningerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/FRestgaeld6")]
    public partial class LAANID {
        
        private string laaneidentifikationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Laaneidentifikation {
            get {
                return this.laaneidentifikationField;
            }
            set {
                this.laaneidentifikationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/FRestgaeld6")]
    public partial class KTRLKD {
        
        private string reference_nrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Reference_nr {
            get {
                return this.reference_nrField;
            }
            set {
                this.reference_nrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/FRestgaeld6")]
    public partial class EJDMID {
        
        private KTRLKD kTRLKDField;
        
        private string ejendomsidentField;
        
        /// <remarks/>
        public KTRLKD KTRLKD {
            get {
                return this.kTRLKDField;
            }
            set {
                this.kTRLKDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Ejendomsident {
            get {
                return this.ejendomsidentField;
            }
            set {
                this.ejendomsidentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/FRestgaeld6")]
    public partial class INSTIT {
        
        private Kodeliste4 institutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Kodeliste4 Institut {
            get {
                return this.institutField;
            }
            set {
                this.institutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/FRestgaeld6")]
    public enum Kodeliste4 {
        
        /// <remarks/>
        PRI,
        
        /// <remarks/>
        EJP,
        
        /// <remarks/>
        SKA,
        
        /// <remarks/>
        SPK,
        
        /// <remarks/>
        STA,
        
        /// <remarks/>
        STK,
        
        /// <remarks/>
        BRF,
        
        /// <remarks/>
        DLR,
        
        /// <remarks/>
        DK,
        
        /// <remarks/>
        HKK,
        
        /// <remarks/>
        LRF,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        RD,
        
        /// <remarks/>
        TOT,
        
        /// <remarks/>
        UNI,
        
        /// <remarks/>
        FK,
        
        /// <remarks/>
        GI,
        
        /// <remarks/>
        IHF,
        
        /// <remarks/>
        IRF,
        
        /// <remarks/>
        JK,
        
        /// <remarks/>
        KI,
        
        /// <remarks/>
        PRF,
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        BGK,
        
        /// <remarks/>
        NOR,
    }
}
