//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace SEgne6 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.realkreditnettet.dk/SEgne6")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.realkreditnettet.dk/SEgne6", IsNullable=false)]
    public partial class SEgne6 {
        
        private DOCINF dOCINFField;
        
        private FJLTXT[] fJLTXTField;
        
        private INSTIT[] iNSTITField;
        
        /// <remarks/>
        public DOCINF DOCINF {
            get {
                return this.dOCINFField;
            }
            set {
                this.dOCINFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FJLTXT")]
        public FJLTXT[] FJLTXT {
            get {
                return this.fJLTXTField;
            }
            set {
                this.fJLTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("INSTIT")]
        public INSTIT[] INSTIT {
            get {
                return this.iNSTITField;
            }
            set {
                this.iNSTITField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/SEgne6")]
    public partial class DOCINF {
        
        private Meddelelsens_navn meddelelsens_navnField;
        
        private bool meddelelsens_navnFieldSpecified;
        
        private Meddelelsens_type meddelelsens_typeField;
        
        private bool meddelelsens_typeFieldSpecified;
        
        private string sender_versionField;
        
        private string modtager_versionField;
        
        private string onsket_versionField;
        
        private string informationsstromsnavnField;
        
        private string meddelelsens_nummerField;
        
        private string meddelelsesnr_for_foresporgselenField;
        
        private Kodeliste5 meddelelsens_funktionField;
        
        private Kodeliste26 meddelelsensstatusField;
        
        private bool meddelelsensstatusFieldSpecified;
        
        private string niveaudelingField;
        
        private string datoField;
        
        private string afsender_partidField;
        
        private string iDkodeField;
        
        private string virksomhedsIDField;
        
        private string afdelingsidField;
        
        private string personidField;
        
        private string modtager_partidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Meddelelsens_navn Meddelelsens_navn {
            get {
                return this.meddelelsens_navnField;
            }
            set {
                this.meddelelsens_navnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Meddelelsens_navnSpecified {
            get {
                return this.meddelelsens_navnFieldSpecified;
            }
            set {
                this.meddelelsens_navnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Meddelelsens_type Meddelelsens_type {
            get {
                return this.meddelelsens_typeField;
            }
            set {
                this.meddelelsens_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Meddelelsens_typeSpecified {
            get {
                return this.meddelelsens_typeFieldSpecified;
            }
            set {
                this.meddelelsens_typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Sender_version {
            get {
                return this.sender_versionField;
            }
            set {
                this.sender_versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Modtager_version {
            get {
                return this.modtager_versionField;
            }
            set {
                this.modtager_versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Onsket_version {
            get {
                return this.onsket_versionField;
            }
            set {
                this.onsket_versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Informationsstromsnavn {
            get {
                return this.informationsstromsnavnField;
            }
            set {
                this.informationsstromsnavnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Meddelelsens_nummer {
            get {
                return this.meddelelsens_nummerField;
            }
            set {
                this.meddelelsens_nummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Meddelelsesnr_for_foresporgselen {
            get {
                return this.meddelelsesnr_for_foresporgselenField;
            }
            set {
                this.meddelelsesnr_for_foresporgselenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Kodeliste5 Meddelelsens_funktion {
            get {
                return this.meddelelsens_funktionField;
            }
            set {
                this.meddelelsens_funktionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Meddelelsens-status")]
        public Kodeliste26 Meddelelsensstatus {
            get {
                return this.meddelelsensstatusField;
            }
            set {
                this.meddelelsensstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MeddelelsensstatusSpecified {
            get {
                return this.meddelelsensstatusFieldSpecified;
            }
            set {
                this.meddelelsensstatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Niveaudeling {
            get {
                return this.niveaudelingField;
            }
            set {
                this.niveaudelingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Dato {
            get {
                return this.datoField;
            }
            set {
                this.datoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Afsender_partid {
            get {
                return this.afsender_partidField;
            }
            set {
                this.afsender_partidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ID-kode")]
        public string IDkode {
            get {
                return this.iDkodeField;
            }
            set {
                this.iDkodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VirksomhedsID {
            get {
                return this.virksomhedsIDField;
            }
            set {
                this.virksomhedsIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Afdelingsid {
            get {
                return this.afdelingsidField;
            }
            set {
                this.afdelingsidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Personid {
            get {
                return this.personidField;
            }
            set {
                this.personidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Modtager_partid {
            get {
                return this.modtager_partidField;
            }
            set {
                this.modtager_partidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/SEgne6")]
    public enum Meddelelsens_navn {
        
        /// <remarks/>
        Z01,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/SEgne6")]
    public enum Meddelelsens_type {
        
        /// <remarks/>
        MORDOC,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/SEgne6")]
    public enum Kodeliste5 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("53")]
        Item53,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/SEgne6")]
    public enum Kodeliste26 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        Z01,
        
        /// <remarks/>
        Z02,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/SEgne6")]
    public partial class LAANOP {
        
        private Kodeliste23 laanetypeField;
        
        private bool laanetypeFieldSpecified;
        
        private string antal_debitor_terminerField;
        
        private decimal tilbudskursField;
        
        private string kursdatoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Kodeliste23 Laanetype {
            get {
                return this.laanetypeField;
            }
            set {
                this.laanetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LaanetypeSpecified {
            get {
                return this.laanetypeFieldSpecified;
            }
            set {
                this.laanetypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Antal_debitor_terminer {
            get {
                return this.antal_debitor_terminerField;
            }
            set {
                this.antal_debitor_terminerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Tilbudskurs {
            get {
                return this.tilbudskursField;
            }
            set {
                this.tilbudskursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Kursdato {
            get {
                return this.kursdatoField;
            }
            set {
                this.kursdatoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/SEgne6")]
    public enum Kodeliste23 {
        
        /// <remarks/>
        K,
        
        /// <remarks/>
        O,
        
        /// <remarks/>
        OM,
        
        /// <remarks/>
        KM,
        
        /// <remarks/>
        KO,
        
        /// <remarks/>
        RF,
        
        /// <remarks/>
        P,
        
        /// <remarks/>
        RP,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        SA,
        
        /// <remarks/>
        J,
        
        /// <remarks/>
        JA,
        
        /// <remarks/>
        U,
        
        /// <remarks/>
        OE,
        
        /// <remarks/>
        OA,
        
        /// <remarks/>
        KOA,
        
        /// <remarks/>
        RPA,
        
        /// <remarks/>
        OV,
        
        /// <remarks/>
        OAV,
        
        /// <remarks/>
        VOM,
        
        /// <remarks/>
        VOU,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/SEgne6")]
    public partial class KURSOP {
        
        private decimal nomoblrenteField;
        
        private decimal loebetidField;
        
        private Kodeliste6 obltypeField;
        
        private Kodeliste1 konvertibelField;
        
        private string kredtermField;
        
        private Kodeliste4 bruger_institutField;
        
        private Kodeliste4 udstedende_institutField;
        
        private string seriebetegnelseField;
        
        private string afdelingsbetegnelseField;
        
        private string oprudloebField;
        
        private Kodeliste1 soledarisk_haeftelseField;
        
        private string udbud_fra_datoField;
        
        private string udbud_til_datoField;
        
        private string gaelder_fraField;
        
        private string gaelder_tilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Nom-obl-rente")]
        public decimal Nomoblrente {
            get {
                return this.nomoblrenteField;
            }
            set {
                this.nomoblrenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Loebetid {
            get {
                return this.loebetidField;
            }
            set {
                this.loebetidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Obl-type")]
        public Kodeliste6 Obltype {
            get {
                return this.obltypeField;
            }
            set {
                this.obltypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Kodeliste1 Konvertibel {
            get {
                return this.konvertibelField;
            }
            set {
                this.konvertibelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Kred-term", DataType="integer")]
        public string Kredterm {
            get {
                return this.kredtermField;
            }
            set {
                this.kredtermField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Kodeliste4 Bruger_institut {
            get {
                return this.bruger_institutField;
            }
            set {
                this.bruger_institutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Kodeliste4 Udstedende_institut {
            get {
                return this.udstedende_institutField;
            }
            set {
                this.udstedende_institutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Seriebetegnelse {
            get {
                return this.seriebetegnelseField;
            }
            set {
                this.seriebetegnelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Afdelingsbetegnelse {
            get {
                return this.afdelingsbetegnelseField;
            }
            set {
                this.afdelingsbetegnelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("Opr-udloeb", DataType="integer")]
        public string Oprudloeb {
            get {
                return this.oprudloebField;
            }
            set {
                this.oprudloebField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Kodeliste1 Soledarisk_haeftelse {
            get {
                return this.soledarisk_haeftelseField;
            }
            set {
                this.soledarisk_haeftelseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Udbud_fra_dato {
            get {
                return this.udbud_fra_datoField;
            }
            set {
                this.udbud_fra_datoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Udbud_til_dato {
            get {
                return this.udbud_til_datoField;
            }
            set {
                this.udbud_til_datoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Gaelder_fra {
            get {
                return this.gaelder_fraField;
            }
            set {
                this.gaelder_fraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string Gaelder_til {
            get {
                return this.gaelder_tilField;
            }
            set {
                this.gaelder_tilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/SEgne6")]
    public enum Kodeliste6 {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        U,
        
        /// <remarks/>
        AAF,
        
        /// <remarks/>
        SAF,
        
        /// <remarks/>
        AV,
        
        /// <remarks/>
        AAV,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/SEgne6")]
    public enum Kodeliste1 {
        
        /// <remarks/>
        Ja,
        
        /// <remarks/>
        Nej,
        
        /// <remarks/>
        IA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/SEgne6")]
    public enum Kodeliste4 {
        
        /// <remarks/>
        PRI,
        
        /// <remarks/>
        EJP,
        
        /// <remarks/>
        SKA,
        
        /// <remarks/>
        SPK,
        
        /// <remarks/>
        STA,
        
        /// <remarks/>
        STK,
        
        /// <remarks/>
        BRF,
        
        /// <remarks/>
        DLR,
        
        /// <remarks/>
        DK,
        
        /// <remarks/>
        HKK,
        
        /// <remarks/>
        LRF,
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        RD,
        
        /// <remarks/>
        TOT,
        
        /// <remarks/>
        UNI,
        
        /// <remarks/>
        FK,
        
        /// <remarks/>
        GI,
        
        /// <remarks/>
        IHF,
        
        /// <remarks/>
        IRF,
        
        /// <remarks/>
        JK,
        
        /// <remarks/>
        KI,
        
        /// <remarks/>
        PRF,
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        BGK,
        
        /// <remarks/>
        NOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/SEgne6")]
    public partial class FONKOD {
        
        private KURSOP kURSOPField;
        
        private LAANOP[] lAANOPField;
        
        private string fondskodeField;
        
        private string valutakodeField;
        
        /// <remarks/>
        public KURSOP KURSOP {
            get {
                return this.kURSOPField;
            }
            set {
                this.kURSOPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LAANOP")]
        public LAANOP[] LAANOP {
            get {
                return this.lAANOPField;
            }
            set {
                this.lAANOPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Fondskode {
            get {
                return this.fondskodeField;
            }
            set {
                this.fondskodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Valutakode {
            get {
                return this.valutakodeField;
            }
            set {
                this.valutakodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/SEgne6")]
    public partial class INSTIT {
        
        private FONKOD[] fONKODField;
        
        private Kodeliste4 institutField;
        
        private bool institutFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FONKOD")]
        public FONKOD[] FONKOD {
            get {
                return this.fONKODField;
            }
            set {
                this.fONKODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Kodeliste4 Institut {
            get {
                return this.institutField;
            }
            set {
                this.institutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InstitutSpecified {
            get {
                return this.institutFieldSpecified;
            }
            set {
                this.institutFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.realkreditnettet.dk/SEgne6")]
    public partial class FJLTXT {
        
        private string fejlkodeField;
        
        private string fejltekstField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Fejlkode {
            get {
                return this.fejlkodeField;
            }
            set {
                this.fejlkodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Fejltekst {
            get {
                return this.fejltekstField;
            }
            set {
                this.fejltekstField = value;
            }
        }
    }
}
